"use client";

import { withAuthenticator } from '@aws-amplify/ui-react';
import { Amplify } from 'aws-amplify';
import outputs from '@/amplify_outputs.json';
import '@aws-amplify/ui-react/styles.css';
import '@/app/globals.css';

// configure the Amplify client library with the configuration generated by `ampx sandbox`
Amplify.configure(outputs);

function AuthPage() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen">
      <h1 className="text-2xl font-bold">You are authenticated!</h1>
    </div>
  );
}

export default withAuthenticator(AuthPage);